[package]
name = "chda-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chda-config.workspace = true
chda-core.workspace = true
chda-term.workspace = true
serde_json.workspace = true
futures.workspace = true
gpui.workspace = true
gpui_platform.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
objc2.workspace = true
objc2-app-kit = { workspace = true, features = ["NSApplication", "NSDockTile", "NSResponder", "NSWindow"] }
objc2-foundation = { workspace = true, features = ["NSBundle", "NSError", "NSLocale", "NSString"] }
objc2-user-notifications = { workspace = true, features = [
    "block2",
    "UNNotification",
    "UNNotificationContent",
    "UNNotificationRequest",
    "UNNotificationResponse",
    "UNNotificationSound",
    "UNNotificationTrigger",
    "UNUserNotificationCenter",
] }

[lints]
workspace = true
