#!/usr/bin/env bash
# Pack the Ghostty themes of an iTerm2-Color-Schemes release (the source
# Ghostty bundles too) into one file chda embeds.
#
#   scripts/update-themes.sh <release tag, e.g. release-20260928-151043-99d9701>
set -euo pipefail

cd "$(dirname "$0")/.."
tag="$1"
assets=crates/chda-config/assets
base=https://github.com/mbadolato/iTerm2-Color-Schemes
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl -fsSL "$base/releases/download/$tag/ghostty-themes.tgz" | tar xz -C "$tmp"
curl -fsSL "https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/${tag##*-}/LICENSE" \
  > "$assets/themes-LICENSE.txt"

{
  echo "# Ghostty themes from iTerm2-Color-Schemes $tag (MIT, see themes-LICENSE.txt)."
  echo "# Generated by scripts/update-themes.sh; do not edit."
  find "$tmp/ghostty" -type f | LC_ALL=C sort | while IFS= read -r file; do
    printf '[%s]\n' "$(basename "$file")"
    grep -Ev '^[[:space:]]*(#|$)' "$file"
  done
} > "$assets/themes.txt"

echo "$(grep -c '^\[' "$assets/themes.txt") themes from $tag"
