[package]
name = "chda-term"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chda-pty.workspace = true
libghostty-vt.workspace = true
regex.workspace = true

[lints]
workspace = true
